language: php

node_js:
  - "0.10"

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  matrix:
    - DB=mysql


matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 5.4
      env: DB=sqlite
    - php: 5.4
      env: DB=pgsql

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh treebookmarks master $DB
  - cd ../core
  - php occ app:enable treebookmarks

before_script:
  - cd apps/treebookmarks
  - npm install
  
script:
  - grunt
